### ISSUE TITLE
Hottest files in last hour with Access Count 0

### ISSUE THREAD

**Issue by ChenSammi** [Intel-bigdata/SSM#683] opened 2017-07-12 01:35 UTC
File ID | File Path | Access Count
-- | -- | --
16405 | /benchmarks/TestDFSIO/io_data/test_io_2 | 0
16404 | /benchmarks/TestDFSIO/io_data/test_io_1 | 0
16403 | /benchmarks/TestDFSIO/io_data/test_io_0 | 0

**Comment by huafengw** [comment] 2017-07-12 02:05
Is it the result shown in dashboard?

**Comment by ChenSammi** [comment] 2017-07-12 02:09
Right, very odd!

**Comment by huafengw** [comment] 2017-07-12 02:23
Is it easy to reproduce this issue?

**Comment by ChenSammi** [comment] 2017-07-12 17:03
Not easy to reproduce. Will continue monitor this issue

**Comment by ChenSammi** [comment] 2017-07-12 23:13
Just leave the UI on hot files page, after some while, it will turn to '0', and will never come back, even after refresh the page.

**Comment by huafengw** [comment] 2017-07-13 01:34
Currently we will only show the hottest files in last hour. So eventually these metrics will fade away if there is no further access event. But still, it's strange that it shows the value zero.

**Comment by ChenSammi** [comment] 2017-07-13 02:08
It only takes several minutes to become value zero. I 'm sure it's not because of out of the 1 hour window.

**Comment by huafengw** [comment] 2017-07-13 02:40
Reproduced this issue and known where it comes from. Working on it.

**Comment by huafengw** [comment] 2017-07-13 05:52
Work-around fixed in #705, it's kind of a nature flaw caused by current design.

**Closed by huafengw** 2017-07-13 05:52 UTC
