### ISSUE TITLE
 Cannot view all action history

### ISSUE THREAD

**Issue by ChenSammi** [Intel-bigdata/SSM#677] opened 2017-07-11 18:43 UTC
Only maximum 20 action history are shown on action table.  Is it a bug or a feature? 

Besides, action with aid & cid "0" is not shown on UI

**Comment by littlezhou** [comment] 2017-07-12 01:32
Maximum 20 actions is a feature. Please check whether the action with aid & cid "0" is in that range or not.

**Comment by ChenSammi** [comment] 2017-07-12 01:38
I remembered when action has more than 20 records,  you press the "id" column to let the sort by "id", record with id "0" is never showed.

**Comment by huafengw** [comment] 2017-07-12 01:40
Yes, it only sort the results returned by backend

**Comment by littlezhou** [comment] 2017-07-12 02:28
Only 20 newest actions will be returned. This issue is not a bug.

**Comment by huafengw** [comment] 2017-07-14 05:37
I think we can close this one now

**Closed by huafengw** 2017-07-14 05:37 UTC
