### ISSUE TITLE
Compress/Decompress actions lead to owner related issues

### ISSUE THREAD

**Issue by lipppppp** [Intel-bigdata/SSM#2194] opened 2020-09-14 03:04 UTC
Hi, I found two issues about compress action.
1.The files owner is changed after compress/decompress action. It may cause permission issue. User hdfs is the admin user of SSM.
![image](https://user-images.githubusercontent.com/32612402/93038873-abf9ba80-f678-11ea-8785-6e2b3ab22049.png)
![image](https://user-images.githubusercontent.com/32612402/93038902-c16ee480-f678-11ea-91f5-2fe26fca3005.png)
![image](https://user-images.githubusercontent.com/32612402/93038917-caf84c80-f678-11ea-9a8f-5f9177ac4b30.png)
2.The shell command 'chown' failed when it set to the directory which have compressed files. It seems HdfsNamedFileStatus is not subclass of LocatedFileStatus.
![image](https://user-images.githubusercontent.com/32612402/93039412-fdef1000-f679-11ea-87aa-b4fd3b3da01c.png)

**Comment by philo-he** [comment] 2020-09-14 06:31
1. Please try to call dfsClient to setOwner to keep consistent ownership. You can do that in (de)CompressAction.
2. I cannot reproduce the issue. From my analysis, HdfsNamedFileStatus cannot be created for compressed file seemingly, assuming files under that folder are correctly compressed. Please have a remote debug to see which kind of file caused this issue.

**Comment by lipppppp** [comment] 2020-09-16 13:13
Thanks for @PHILO-HE 's support. PR#2195 solved this problem.

**Comment by philo-he** [comment] 2020-09-17 05:17
OK. Let's close this issue.

**Closed as completed by philo-he** 2020-09-17 05:17 UTC
